#!/usr/bin/ruby
# frozen_string_literal: true

system 'clear'
# Making a better cp Making a better mv Making a better shred Making a better cat Making a better tac Making a better find Making a better big_num Making a better xargs Making a better mvmulti Making a better c_repl Making a better sed
if Dir.home == '/root'
  puts "Don't run as root"
  exit
end
topics = File.open '/usr/share/topics'
# UNDONE_TOPICS = 'Making a better '
# end

def ask(question)
  print "#{question}? "
  begin
    $stdin.readline
  rescue Exception
    puts
    exit
  end
end

# puts "Going to make"
# puts topics.inspect

# topics.times { |number| print(number + 1, " ", topi)}
topics.each do |topic|
  system "which toilet || apt install toilet -y || su -c 'yum install toilet'"
  system "toilet -w 200 #{topic.upcase}"
  # system "(echo #{topic.upcase} || () | toilet -w 200"
  # begin
  # puts Enter video name

  topics.size.times do |number|
    print "#{number + 1}. #{topics[number]}\n"
  end

  # puts "Press enter to take a recording! "

  system "kazam 2>/dev/null && clear; google-chrome 'studio.youtube.com' 1>/dev/null 2>/dev/null & "

  f = "#{Dir.home}/.TMP_JAVASCRIPT_CODE"

  File.open(f, 'w') do |code|
    code.puts <<~EOF
      console.clear();
      function f() { /*window.location.href = "https://www.youtube.com/"; */ let $=function(_){return document.querySelector(_); };  try { $("#create-icon > div").click(); $("#text-item-0 > ytcp-ve > div > div > yt-formatted-string").click(); $("#select-files-button > div").click(); } catch (_) { return; }; console.log("cleared interval");clearInterval(e); }; e = setInterval(f, 200);

      q = setInterval(function() {
      try {
      document.querySelector("#close-button > div"); document.querySelector('[name="NOT_MADE_FOR_KIDS"]').click()

      //document.querySelector("#text-input").textContent='


      //'
      a= [...document.querySelectorAll("#textbox")]; b=a[1];a=a[0]; a.textContent = "An Introduction to PLAY, a Tool for Linux/Unix to Enable More Interactive Computer and Internet Use"; b.textContent = `

      WARNING: In the first two or so minutes of the video, the audio cuts off. FORTUNATELY, THE VIDEO IS STILL COMPLETELY COMPREHENSIBLE.

      (The graphics card of the laptop that I'm using is kind of messed up I think. Oh well.)

      In this video I show "open", which is one of the most practical computer programs ever created. USABLE FOR ALL USERS, NOT JUST PROGRAMMING TYPES.


      -----------------------------------------------------

      www.ethicify.online/improve_the_world/tools

      FOR HACKERS/DEVELOPERS
      ---------------------------------------------------------------------------------




      Another program that I would like to make would be a less problematic version of xargs.

      How many times have to used xargs awkwardly? What with the -print0 nonsense?

      I want find 2&gt;/dev/null | args cat to work perfectly, even for files with spaces

      Feel free to contribute your own tools, particularly if the source code is very simple and readable.

      I recommend that developers use Crystal, D or Nim, because those languages are fast.

      Go could also work.

      I am also working on a C preprocessor. I have the goal of making a variant of C that is

      1. just C
      2. faster than C (I can use functions that are faster versions of things, i.e., memcpy, and I can avoid things like strlen
      3) HIGHER LEVEL than bash`

      } catch (exception) {
      	return;
      }

      //clearInterval(q);
      }, 100);


    EOF
  end

  loop do
    system "xclip -selection c #{f}"
    print 'Press enter to get tags > '
    gets
    system 'echo linux,unix,terminal,bash,bsd,free software,server,coreutils,gnu,gregory,cohen,mint,ubuntu,debian,programming,crystal,google,chrome,browser,web,play,music,espeak,speak,gnome,kde,math,mathematics,tts,exponentiation,trump,biden,news,interactivity,interfaces,firefox,south america,americas,tab,tabs,manifest,display,audio,songs,offical,video,drivers,license,open source,free,download,freeware,ruby,crystallang,core utilities,utility,tool,tools,core,email,open,shell,productivity,window,pictures | xclip -selection c'
    system 'clear'
  end
  'rescue Exception
system "clear; rm #{f}"
raise
end
rescue Exception
system "killall gnome-terminal konsole"
break
end'
end
