#!/bin/bash

espeak One
cd s; (for ((i=1;i<=420;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 420
espeak One

cd s; (for ((i=1;i<=150;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 150
espeak One

cd s; (for ((i=1;i<=50;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 50
espeak One

cd s; (for ((i=1;i<=90;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 90
espeak One

cd s; (for ((i=1;i<=10;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 10
espeak One

cd s; (for ((i=1;i<=5;++i));do                 ../c_program_faster $i 1.05;   done) | fgrep -v 'Fewer'   |   grep -P 'Sale on.*Sale on.*Sale on' | t 'i.split("Sale on")[0] if i[0].to_s.match /[A-Z]/' | sort | uniq -c | sort -h | t i.strip | tail > 5

espeak One


tput reset
echo These are the best stocks that exist for 1.05 reselling
echo Put all your money into them
cat 420 150 50 90 10 5| selectlines | t i.split[1] | sort | uniq -c | tee REAL_BEST_STOCKS

#cat REAL_BEST_STOCKS                              
