#!/usr/bin/ruby

a = File.read "/home/a/tsx"
a  =a.split


require "fileutils"
FileUtils.cd"/home/a/s"
#system 'find -size 0 -exec rm {} \;'
#Dir.chdir "/home/a/s"

a.each do |w|
	%w[.TO -A.TO .V .CN].each {|end_|
		end_ = w + end_
		if test "e", end_
		puts "Skipping #{end_}"
		next
		end
		system "python3 /home/a/a.py " + end_ + " > " + end_
#	end
	}
end


puts a